# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MasonryAnimation' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'Masonry', '~> 1.1.0'
  # Pods for MasonryAnimation

  target 'MasonryAnimationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MasonryAnimationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
