# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MJExtension' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'MJExtension', '~> 3.0.15.1'
  # Pods for MJExtension

end
